Change workflows

diff --git a/.github/workflows/quality.yml b/.github/workflows/quality.yml
--- a/.github/workflows/quality.yml
+++ b/.github/workflows/quality.yml
@@ -60,3 +60,64 @@ jobs:
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: results.sarif
+  rust-quality-gate:
+    name: Rust Quality Gate
+    env:
+      working-directory: "role-manager"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Install Rust
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
+      
+      - name: Build code
+        run: cargo build --all --release
+        working-directory: ${{ env.working-directory }}
+        
+      - name: Format code with Rustfmt
+        run: cargo fmt --all -- --check
+        working-directory: ${{ env.working-directory }}
+        continue-on-error: true
+        id: rustfmt
+
+      - name: Run Clippy
+        run: cargo clippy --all -- -D warnings
+        working-directory: ${{ env.working-directory }}
+        continue-on-error: true
+        id: clippy
+      
+      - name: Check errors and set workflow status
+        run: |
+          if [[ ${{ steps.rustfmt.outcome }} == 'failure' ]]; then
+            echo "Error: Rustfmt failed."
+            exit 1
+          fi
+          if [[ ${{ steps.clippy.outcome }} == 'failure' ]]; then
+            echo "Error: Clippy failed."
+            exit 1
+          fi
+        if: ${{ always() }}
+  rust-security:
+    name: Rust Security Gate
+    env:
+      working-directory: "role-manager"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Install Rust
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
+      
+      - name: Cargo audit
+        run: cargo audit --json | tee cargo-audit.json
+        working-directory: ${{ env.working-directory }}
+        id: cargo-audit
